#!/bin/sh

DIRS="`echo deps/{core,dev,web,contrib}` base async-servlet cljs enlive.cljs enlive.clj handler server"

for d in $DIRS; do
    echo "Running '$@' in $d"
    (cd $d && exec $@)
    echo "... finished"
    echo "---------------------------------"
done
