#!/bin/sh

set -e

gra () {
    local repo="webnf/$1"
    local rbranch="$repo/$2"
    git remote add $repo $3:$repo
    git fetch $repo
    git-new-workdir . $1
    (cd $1
     git checkout -b $repo $rbranch)
}

for dir in dwn lein-nix lein-collisions
 do gra $dir master git@github.com; done
